terraform {
  required_providers {
    stripe = {
      source  = "stripe/stripe"
      version = "~> 0.2.1"
    }
  }
}

variable "stripe_api_key" {
  description = "Stripe API key used by the Terraform Stripe provider. Set via TF_VAR_stripe_api_key."
  type        = string
  sensitive   = true
}

provider "stripe" {
  api_key = var.stripe_api_key
}


variable "webhook_endpoint_url" {
  description = "Public URL for the generated app's Stripe webhook route. Set this after deployment, for example https://example.com/api/webhooks/stripe."
  type        = string
  default     = ""
}


resource "stripe_product" "one_time_purchase" {
  name        = "Next.js One-time Payment Render Starter Starter"
  description = "Starter one-time purchase generated by stripe build."
}

resource "stripe_price" "one_time_purchase" {
  product     = stripe_product.one_time_purchase.id
  currency    = "usd"
  unit_amount = 1000
}


resource "stripe_webhook_endpoint" "purchase_checkout" {
  count = trimspace(var.webhook_endpoint_url) == "" ? 0 : 1

  url            = var.webhook_endpoint_url
  description    = "Starter purchase unlock webhook generated by stripe build."
  enabled_events = ["checkout.session.completed"]
}


output "product_id" {
  description = "Stripe product ID for the generated one-time purchase."
  value       = stripe_product.one_time_purchase.id
}

output "price_id" {
  description = "Stripe price ID for the generated one-time purchase. Add this to STRIPE_PRICE_ID in your app environment."
  value       = stripe_price.one_time_purchase.id
}


output "webhook_secret" {
  description = "Stripe webhook signing secret for app/api/webhooks/stripe. Empty until webhook_endpoint_url is configured and applied."
  value       = trimspace(var.webhook_endpoint_url) == "" ? "" : stripe_webhook_endpoint.purchase_checkout[0].secret
  sensitive   = true
}

